package com.back.guessgame.repository.dto;

public enum ActionType {
	ADD_POINTS, LOOSE_POINTS, ADD_POINTS_BY_DATE, END_GAME, START_GAME, USER_READY, USER_NOT_READY, USER_JOIN, USER_LEAVE, END_PARTY, START_PARTY, USER_WIN, USER_LOOSE, END_ROUND, START_ROUND, FASTER_WIN, FASTER_WIN_BY_ROUND, PERSONAL_GAME_END, NEXT_GAME;
}
